### PR TITLE
added my bio

### PR DESCRIPTION
**Pull request by olekongithub**

### CODE REVIEW

**Comment by EvanMisshula** [comment]
I am going to fix this.  I just want you to know that Pelican takes the markdown files and generate (or regenerates) html based on them.  Your changes would get wiped out.

**Comment by olekongithub** [comment]
Ah I wasn't aware I had to do this through pelican, sorry. I'll try to
familiarize myself with it.

**Comment by AryanJ-NYC** [comment]
This means any HTML we want to keep should be added to the .md instead of the .html, correct?

**Comment by EvanMisshula** [comment]
That is correct.  But most of the time you will want to add css to the css folder.

**Pull request closed without merging**
